CREATE TABLE kid (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    dob DATE,
    household_id INTEGER,
    current_stars TINYINT, 
    created_at TIMESTAMP DEFAULT now() NOT NULL
)