CREATE TABLE action (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    action TEXT NOT NULL,
    dob DATE,
    child_id INTEGER,
    polarity BOOLEAN, 
    created_at TIMESTAMP DEFAULT now() NOT NULL
)